[package]
authors = ["The Veracruz Development Team"]
description = "Reads a file, and then compresses it using the huffman encoding algorithm. Finally, writes the output into another text file"
name = "huffman-encoding"
version = "0.3.0"
edition = "2018"

[dependencies]
anyhow = "1.0.14"
