[package]
authors = ["The Veracruz Development Team"]
description = "Reading a file contains and unsorted numbers, sort them and write the output into a text file"
name = "sort-numbers"
version = "0.3.0"
edition = "2018"

[dependencies]
anyhow = "1.0.14"
