# workspaces/host/Cargo.toml:
# Workspace for locally-run programs
#
# AUTHORS
#
# The Veracruz Development Team.
#
# COPYRIGHT
#
# See the `LICENSE_MIT.markdown` file in the Veracruz root director for licensing
# and copyright information.

cargo-features = ["resolver"]

[workspace]
exclude = [
  "crates/third-party/rust-mbedtls",
  "crates/third-party/wasmi",
]
members = [
  "crates/freestanding-execution-engine",
  "crates/generate-policy",
]
resolver = "2"

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
