[package]
authors = ["The Veracruz Development Team"]
description = "The test program for calling the postcard native module."
name = "postcard-native"
version = "0.3.0"
edition = "2018"

[dependencies]
anyhow = "1.0.14"
