# workspaces/linux-host/Cargo.toml:
# Workspace for untrusted Linux services and tests
#
# AUTHORS
#
# The Veracruz Development Team.
#
# COPYRIGHT
#
# See the `LICENSE.md` file in the Veracruz root director for licensing
# and copyright information.

cargo-features = ["resolver"]

[workspace]
exclude = [
  "crates/nitro-veracruz-server",
  "crates/third-party/rust-mbedtls",
]
members = [
  "crates/veracruz-client",
  "crates/veracruz-server",
  "crates/linux-veracruz-server",
  "crates/tests",
  "src/linux-host",
]
resolver = "2"

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
[patch.'https://github.com/veracruz-project/nitro-enclave']
raw-fd = { git = "https://github.com//veracruz-project/nitro-enclave", branch = "dreemkiller_expose_vsocket" }
vsocket = { git = "https://github.com//veracruz-project/nitro-enclave", branch = "dreemkiller_expose_vsocket" }
[patch.'https://github.com/veracruz-project/proxy-attestation-client']
proxy-attestation-client = {  git = "https://github.com//veracruz-project/proxy-attestation-client", branch = "dreemkiller_add_sev" }
