name: Build Docker Image

on:
  # Only run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write
    steps:
      - name: Check out the Veracruz repository
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1
        with:
          submodules: false

      - name: Login to GitHub Container Registry
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install cosign
        # https://github.com/sigstore/cosign-installer
        uses: sigstore/cosign-installer@9becc617647dfa20ae7b1151972e9b3a2c338a2b # v2.8.1
        with:
          cosign-release: "v1.13.1"

      - name: Build Docker Image
        id: docker-build
        run: |
          make -C docker ci-image DOCKER_BUILD_CMD="docker buildx build" EXTRA_BUILD_ARGS="--cache-from=type=gha --cache-to=type=gha,mode=max"
          make -C docker ci-image-tag
          make -C docker ci-image-push
          make -C docker ci-image-sign
