name: Veracruz-CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Install cosign
        # https://github.com/sigstore/cosign-installer
        uses: sigstore/cosign-installer@9becc617647dfa20ae7b1151972e9b3a2c338a2b # v2.8.1
        with:
          cosign-release: "v1.13.1"
      - name: Check image signature
        id: cosign-verify
        run: |
            COSIGN_EXPERIMENTAL=true cosign verify \
              ghcr.io/veracruz-project/veracruz/ci@sha256:b5eb834cd58c69e6acc19b1b19c6345a020ad2ad090cdab3bc9f7d5d48fb00ba

  linux:
    runs-on: ubuntu-latest
    needs: [check]
    outputs:
      output: ${{ steps.check-diff.outputs.cargo-lock }}
    container:
      image: ghcr.io/veracruz-project/veracruz/ci@sha256:b5eb834cd58c69e6acc19b1b19c6345a020ad2ad090cdab3bc9f7d5d48fb00ba
      volumes:
        - ${{ github.workspace }}:/work/veracruz
    steps:
      - name: Check out the Veracruz repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: add the GITHUB_WORKSPACE into git config
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Running linux test script
        id: linux-build-and-test
        run: |
            make -C /work/veracruz/workspaces linux-tests
      - name: Move back to veracruz root
        run: cd /work/veracruz
      - name: Check modification to Cargo.lock 
        id: verify-changed-files
        uses: tj-actions/verify-changed-files@v13
        with:
          files: |
            **/Cargo.lock 
      - name: Run step only when any of the above files change.
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        id: check-diff
        run: |
          echo "cargo-lock=\"Detect 'Cargo.lock' changes in ${{ github.job }} CI/CD task: ${{ steps.verify-changed-files.outputs.changed_files }}\"" >> $GITHUB_OUTPUT 

  nitro:
    runs-on: ubuntu-latest
    needs: [check]
    outputs:
      output: ${{ steps.check-diff.outputs.cargo-lock }}
    container:
      image: ghcr.io/veracruz-project/veracruz/ci@sha256:b5eb834cd58c69e6acc19b1b19c6345a020ad2ad090cdab3bc9f7d5d48fb00ba
      volumes:
        - ${{ github.workspace }}:/work/veracruz
    steps:
      - name: Check out the Veracruz repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: add the GITHUB_WORKSPACE into git config
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Running Nitro test script
        id: nitro-build
        run: |
            make -C /work/veracruz/workspaces nitro
      - name: Check modification to Cargo.lock 
        id: verify-changed-files
        uses: tj-actions/verify-changed-files@v13
        with:
          files: |
            **/Cargo.lock 
      - name: Run step only when any of the above files change.
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        id: check-diff
        run: |
          echo "cargo-lock=\"Detect 'Cargo.lock' changes in ${{ github.job }} CI/CD task: ${{ steps.verify-changed-files.outputs.changed_files }}\"" >> $GITHUB_OUTPUT 

  icecap:
    runs-on: ubuntu-latest
    needs: [check]
    outputs:
      output: ${{ steps.check-diff.outputs.cargo-lock }}
    container:
      image: ghcr.io/veracruz-project/veracruz/ci@sha256:b5eb834cd58c69e6acc19b1b19c6345a020ad2ad090cdab3bc9f7d5d48fb00ba
      volumes:
        - ${{ github.workspace }}:/work/veracruz
    steps:
      - name: Check out the Veracruz repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: add the GITHUB_WORKSPACE into git config
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Running IceCap test script
        id: icecap-build
        run: |
            VERACRUZ_TEST_TIMEOUT=2400 make -C /work/veracruz/workspaces icecap-tests PROFILE=release
      - name: Check modification to Cargo.lock 
        id: verify-changed-files
        uses: tj-actions/verify-changed-files@v13
        with:
          files: |
            **/Cargo.lock 
      - name: Run step only when any of the above files change.
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        id: check-diff
        run: |
          echo "cargo-lock=\"Detect 'Cargo.lock' changes in ${{ github.job }} CI/CD task: ${{ steps.verify-changed-files.outputs.changed_files }}\"" >> $GITHUB_OUTPUT 

  # tests that the CLI_QUICKSTART.markdown is still up to date
  quickstart:
    runs-on: ubuntu-latest
    needs: [check]
    outputs:
      output: ${{ steps.check-diff.outputs.cargo-lock }}
    container:
      image: ghcr.io/veracruz-project/veracruz/ci@sha256:b5eb834cd58c69e6acc19b1b19c6345a020ad2ad090cdab3bc9f7d5d48fb00ba
      volumes:
        - ${{ github.workspace }}:/work/veracruz
    steps:
      - name: Check out the Veracruz repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: add the GITHUB_WORKSPACE into git config
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Running CLI_QUICKSTART.markdown
        id: quickstart-test
        run: |
          # grab every bash code block, remove line continuation, and only keep lines
          # that start with '$' (of course removing that '$' in the process)
          sed -n '/``` bash/,/```/{/```/d; p}' CLI_QUICKSTART.markdown \
            | sed ':a; /\\$/{N; s/\\\n//; ta}' \
            | sed -n '/^\$/{s/^\$ \?//; p}' \
            > CLI_QUICKSTART.markdown.sh
          # run the quickstart
          bash -euxo pipefail CLI_QUICKSTART.markdown.sh
      - name: Running tlstest/README.md
        id: tlstest
        run: |
          # Extract and execute bash code blocks from README.md:
          cd tests/tlstest && \
          sed -n '/``` bash/,/```/{/```/d; p}' README.md > README.md.sh && \
          bash -euxo pipefail README.md.sh
      - name: Check modification to Cargo.lock 
        id: verify-changed-files
        uses: tj-actions/verify-changed-files@v13
        with:
          files: |
            **/Cargo.lock 
      - name: Run step only when any of the above files change.
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        id: check-diff
        run: |
          echo "cargo-lock=\"Detect 'Cargo.lock' changes in ${{ github.job }} CI/CD task: ${{ steps.verify-changed-files.outputs.changed_files }}\"" >> $GITHUB_OUTPUT 

  cargo-lock-check:
    needs: [linux, nitro, icecap, quickstart]
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/veracruz-project/veracruz/ci:v22.09
      volumes:
        - ${{ github.workspace }}:/work/veracruz
    steps:
      - name: linux
        if: needs.linux.outputs.output != ''
        run: |
          echo "::warning:: ${{ needs.linux.outputs.output }}" 
          exit 1
      - name: nitro
        if: needs.nitro.outputs.output != ''
        run: |
          echo "::warning:: ${{ needs.nitro.outputs.output }}" 
          exit 1
      - name: icecap
        if: needs.icecap.outputs.output != ''
        run: |
          echo "::warning:: ${{ needs.icecap.outputs.output }}" 
          exit 1
      - name: quickstart
        if: needs.quickstart.outputs.output != ''
        run: |
          echo "::warning:: ${{ needs.quickstart.outputs.output }}" 
          exit 1
