name: Veracruz-CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Install cosign
        # https://github.com/sigstore/cosign-installer
        uses: sigstore/cosign-installer@9becc617647dfa20ae7b1151972e9b3a2c338a2b # v2.8.1
        with:
          cosign-release: "v1.13.1"
      - name: Check image signature
        id: cosign-verify
        run: |
            COSIGN_EXPERIMENTAL=true cosign verify \
              ghcr.io/veracruz-project/veracruz/ci@sha256:b5eb834cd58c69e6acc19b1b19c6345a020ad2ad090cdab3bc9f7d5d48fb00ba

  linux:
    runs-on: ubuntu-latest
    needs: [check]
    container:
      image: ghcr.io/veracruz-project/veracruz/ci@sha256:b5eb834cd58c69e6acc19b1b19c6345a020ad2ad090cdab3bc9f7d5d48fb00ba
      volumes:
        - ${{ github.workspace }}:/work/veracruz
    steps:
      - name: Check out the Veracruz repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Running linux test script
        id: linux-build-and-test
        run: |
            make -C /work/veracruz/workspaces linux-tests

  nitro:
    runs-on: ubuntu-latest
    needs: [check]
    container:
      image: ghcr.io/veracruz-project/veracruz/ci@sha256:b5eb834cd58c69e6acc19b1b19c6345a020ad2ad090cdab3bc9f7d5d48fb00ba
      volumes:
        - ${{ github.workspace }}:/work/veracruz
    steps:
      - name: Check out the Veracruz repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Running Nitro test script
        id: nitro-build
        run: |
            make -C /work/veracruz/workspaces nitro

  icecap:
    runs-on: ubuntu-latest
    needs: [check]
    container:
      image: ghcr.io/veracruz-project/veracruz/ci@sha256:b5eb834cd58c69e6acc19b1b19c6345a020ad2ad090cdab3bc9f7d5d48fb00ba
      volumes:
        - ${{ github.workspace }}:/work/veracruz
    steps:
      - name: Check out the Veracruz repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Running IceCap test script
        id: icecap-build
        run: |
            VERACRUZ_TEST_TIMEOUT=2400 make -C /work/veracruz/workspaces icecap-tests PROFILE=release

  # tests that the CLI_QUICKSTART.markdown is still up to date
  quickstart:
    runs-on: ubuntu-latest
    needs: [check]
    container:
      image: ghcr.io/veracruz-project/veracruz/ci@sha256:b5eb834cd58c69e6acc19b1b19c6345a020ad2ad090cdab3bc9f7d5d48fb00ba
      volumes:
        - ${{ github.workspace }}:/work/veracruz
    steps:
      - name: Check out the Veracruz repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Running CLI_QUICKSTART.markdown
        id: quickstart-test
        run: |
          # grab every bash code block, remove line continuation, and only keep lines
          # that start with '$' (of course removing that '$' in the process)
          sed -n '/``` bash/,/```/{/```/d; p}' CLI_QUICKSTART.markdown \
            | sed ':a; /\\$/{N; s/\\\n//; ta}' \
            | sed -n '/^\$/{s/^\$ \?//; p}' \
            > CLI_QUICKSTART.markdown.sh
          # run the quickstart
          bash -euxo pipefail CLI_QUICKSTART.markdown.sh
      - name: Running tlstest/README.md
        id: tlstest
        run: |
          # Extract and execute bash code blocks from README.md:
          cd tests/tlstest && \
          sed -n '/``` bash/,/```/{/```/d; p}' README.md > README.md.sh && \
          bash -euxo pipefail README.md.sh
